language: cpp

dist: trusty

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
    - sudo apt-get update -qq -y
    - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb
    - sudo apt-get install -y libtinyxml2-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

